name: Build SunamoData

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoData
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoData/SunamoData.csproj

    - name: Build
      run: dotnet build SunamoData/SunamoData.csproj --configuration Release --no-restore

  test:
    name: Test SunamoData.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoData.Tests/SunamoData.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoData.Tests/SunamoData.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoData.Tests/SunamoData.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
